#!/usr/bin/php
<?php

# Copyright (c) 2010-2013 Yubico AB
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set_include_path(get_include_path() . PATH_SEPARATOR . "/usr/share/yubikey-val:/etc/yubico/val");

require_once 'ykval-config.php';
require_once 'ykval-db.php';


$logname="ykval-import";
$myLog = new Log($logname);

$db = Db::GetDatabaseHandle($baseParams, $logname);

if (!$db->connect()) {
  $myLog->log(LOG_WARNING, "Could not connect to database");
  error_log("Could not connect to database");
  exit(1);
 }


while ($res=fgetcsv(STDIN, 0, ",")) {
  if($res[0]===null || strpos($res[0], '#')===0) continue;

  $params=array("active"=>$res[0],
		"created"=>$res[1],
		"modified"=>$res[2],
		"yk_publicname"=>$res[3],
		"yk_counter"=>$res[4],
		"yk_use"=>$res[5],
		"yk_low"=>$res[6],
		"yk_high"=>$res[7],
		"nonce"=>$res[8],
		"notes"=>$res[9]);


  $query="SELECT * FROM yubikeys WHERE yk_publicname='" . $params['yk_publicname'] . "'";
  $result=$db->customQuery($query);
  if($db->rowCount($result)) {
    $query="UPDATE yubikeys SET " .
      "active='" . $params["active"] . "' " .
      ",created='" . $params["created"] . "' " .
      ",modified='" . $params["modified"] . "' " .
      ",yk_counter='" . $params["yk_counter"] . "' " .
      ",yk_use='" . $params["yk_use"] . "' " .
      ",yk_low='" . $params["yk_low"] . "' " .
      ",yk_high='" . $params["yk_high"] . "' " .
      ",nonce='" . $params["nonce"] . "' " .
      ",notes='" . $params["notes"] . "' " .
      "WHERE yk_publicname='" . $params['yk_publicname'] . "' AND " .
      "(".$params['yk_counter'].">yk_counter or (".$params['yk_counter']."=yk_counter and " .
      $params['yk_use'] . ">yk_use))";

    if(!$db->customQuery($query)) {
      $myLog->log(LOG_ERR, "Failed to update yk_publicname with query " . $query);
      error_log("Failed to update yk_publicname with query " . $query);
      exit(1);
    }

  } else {
    // We didn't have the yk_publicname in database so we need to do insert instead
    $query="INSERT INTO yubikeys " .
      "(active,created,modified,yk_publicname,yk_counter,yk_use,yk_low,yk_high,nonce,notes) VALUES " .
      "('" . $params["active"] . "', " .
      "'" . $params['created'] . "'," .
      "'" . $params['modified'] . "'," .
      "'" . $params['yk_publicname'] . "'," .
      "'" . $params['yk_counter'] . "'," .
      "'" . $params['yk_use'] . "'," .
      "'" . $params['yk_low'] . "'," .
      "'" . $params['yk_high'] . "'," .
      "'" . $params['nonce'] . "'," .
      "'" . $params['notes'] . "')";

    if(!$db->customQuery($query)){
      $myLog->log(LOG_ERR, "Failed to insert new yk_publicname with query " . $query);
      error_log("Failed to insert new yk_publicname with query " . $query);
      exit(1);
    }
  }
  $db->closeCursor($result);
 }


$myLog->log(LOG_NOTICE, "Successfully imported yubikeys to database");
echo "Successfully imported yubikeys to database\n";
