= YK-VAL Munin Plugin =

Munin is a powerful system monitoring solution.  See
http://munin-monitoring.org/ for more information.  This document
documents how to install and enable the YK-VAL Munin plugins on a
Munin node.  You need to install and configure Munin before following
these steps.

The following Munin plugins are shipped as part of YK-VAL.  They make
it easy for you to monitor your YK-VAL installation.

* ykval_ksmlatency: Monitor the latency to each KSM.  A useful side
effect is that it tests whether the KSM is operational for the
particular validation server.

* ykval_vallatency: Monitor the latency to the other VAL servers, for
both IPv4 and IPv6.

* ykval_queuelength: Monitor the size of the YK-VAL queue.

The plugins are installed by 'make install' but needs to be configured
before they can be used.  First create a Munin configuration file to
make sure the plugins can access the YK-VAL ykval-config.php
configuration file:

 user@val:~$ sudo sh -c 'cat > /etc/munin/plugin-conf.d/ykval'
 [ykval_ksmlatency]
 group www-data
 [ykval_vallatency]
 group www-data
 [ykval_queuelength]
 group www-data
 user@val:~$

Then check that they are working properly:

 user@val:~$ sudo /usr/sbin/munin-run --servicedir /usr/share/munin/plugins ykval_queuelength autoconf
 yes
 user@val:~$ sudo /usr/sbin/munin-run --servicedir /usr/share/munin/plugins ykval_queuelength config
 graph_title YK-VAL queue size
 graph_vlabel sync requests in queue
 graph_category ykval
 queuelength.label sync requests
 queuelength.draw AREA
 user@val:~$ sudo /usr/sbin/munin-run --servicedir /usr/share/munin/plugins ykval_queuelength 
 queuelength.value 0
 user@val:~$

Enable the plugin as follows:

 user@val:~$ sudo munin-node-configure --shell | sudo sh
 user@val:~$ sudo /etc/init.d/munin-node restart
 Stopping Munin-Node: done.
 Starting Munin-Node: done.
 user@val:~$ 

After some time, you should see new graphs on your Munin master.
