Format of YubiKey Info Data
===========================

This file holds data used in the YubiKey OTP validation phase.

Each of the lines in the file follows the following format:

 active,created,modified,yk_publicname,yk_counter,yk_use,yk_low,yk_high,nonce,notes

Any empty line, or a line beginning with a # is ignored.

The meaning are as follows:

....
 active
  the YubiKey state, 1 if active, 0 if not
 created
  unix timestamp of when the YubiKey entry was created, decimal integer
 modified
  unix timestamp of when the YubiKey entry was last modified, decimal integer
 yk_publicname
  the public id of the YubiKey, modhex string
 yk_counter
  the YubiKey session counter, decimal integer
 yk_use
  the YubiKey use counter, decimal integer
 yk_low
  the low part of the YubiKey timestamp counter, decimal integer
 yk_high
  the high part of the YubiKey timestamp counter, decimal integer
 nonce
  the nonce used for the last validation request, ascii printable string
 notes
  not used, printable ascii string
....

An example of a valid data line:

 1,1359470658,1359470658,cccccccccccb,2,1,32729,4,aoincuhfuahs

For an example of importing and exporting YubiKey Info data, please see
link:ImportExportData.html[ImportExportData]
